# Generated by Django 2.1.4 on 2018-12-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181221_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='turma',
            field=models.ManyToManyField(to='core.Turma'),
        ),
    ]
