# Generated by Django 2.1.4 on 2018-12-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_turma_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='codigo',
            new_name='codigo_da_turma',
        ),
    ]
