# Generated by Django 2.1.4 on 2018-12-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181221_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='codigo_da_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
    ]
